### Instituto Federal de Educação Ciência e Tecnologia de Goias
### Aluno: Alex Augusto Cintra da Fonseca
### Curso: Sistemas de Informação
### Materia: Inteligência Artificial
### Período: 7º

### Teste de Acurácia na Classificação da Aprovação e Reprovação

In [67]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

%matplotlib inline

In [68]:
df = pd.read_csv('curso_clean_final.csv')

In [69]:
df.columns

Index(['SIT_MATRICULA', 'RENDA_FAMILIAR', 'ANO_CONCLUSAO_2_GRAU',
       'RENDA_PER_CAPITA', 'N_FILHOS', 'SEXO', 'PROFISSAO', 'DESC_CIDADE',
       'DESC_IDIOMA', 'NIVEL_FALA', 'NIVEL_COMPREENSAO', 'NIVEL_ESCRITA',
       'NIVEL_LEITURA', 'NOTAS', 'N_FALTAS', 'CARGA_HOR', 'ANO_INGRESSO',
       'IDADE_INGRESSO', 'APROVADO'],
      dtype='object')

Separando os campos relacionados a caracterização do campo aprovação

In [70]:
df_aprovacao = df.loc[:, ['N_FALTAS', 'CARGA_HOR', 'NOTAS', 'APROVADO']].values

In [71]:
X_aprov = df_aprovacao[:, 0:3]
X_aprov

array([[  0. ,  54. ,   6.7],
       [  0. ,  54. ,  10. ],
       [  0. ,  54. ,  10. ],
       ..., 
       [  0. ,  27. ,   7.9],
       [  0. ,  27. ,   8.6],
       [  0. ,  27. ,   8.6]])

In [72]:
y_aprov = df_aprovacao[:,np.newaxis,3].ravel()
y_aprov

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

Trazendo a biblioteca do classificador em kn vizinhos <br>

Para selecionar os vizinhos, é necessário sempre escolher vizinhos impares <br>
Pois vizinhos de valor par, em algum momento causa empate entre dois valores, e a escolha de um ou outro é complicada de se fazer

#### Teste de acurácia da predição do knn

Seleção de vizinhos abaixo

In [79]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_aprov, y_aprov)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [80]:
from sklearn.model_selection import train_test_split

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X_aprov, y_aprov, test_size=0.2, random_state=42)

X_train.shape, y_train.shape

((15597, 3), (15597,))

In [92]:
X_test.shape, y_test.shape

((3900, 3), (3900,))

In [97]:
knn.fit(X_train,y_train)
knn.score(X_test, y_test)

0.99820512820512819

In [94]:
knn = KNeighborsClassifier(n_neighbors=1)

knn.fit(X_train,y_train)
knn.score(X_test, y_test)

0.99923076923076926

In [95]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train,y_train)
knn.score(X_test, y_test)

0.99820512820512819

### Classificação da Evasão de um Aluno (Utilizando-se de acurácia com 3 algoritmos):

#### Para predição da evasão deve-se desconsiderar o target aprovado
#### y irá receber o target situação matricula, enquanto o x recebera todo o resto da base

In [98]:
X_evasao = df.ix[:, 1:18].values
X_evasao

array([[    4.,  2014.,     8., ...,    54.,  2016.,    20.],
       [    0.,  2011.,     0., ...,    54.,  2016.,    21.],
       [    0.,  2011.,     0., ...,    54.,  2016.,    21.],
       ..., 
       [    0.,  2011.,     0., ...,    27.,  2012.,    18.],
       [    0.,  2012.,     0., ...,    27.,  2012.,    17.],
       [    4.,  2007.,     8., ...,    27.,  2012.,    22.]])

In [105]:
y_evasao = df[['SIT_MATRICULA']].values.ravel()
y_evasao

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

#### Treinamento dos valores selecionados

In [106]:
from sklearn.model_selection import train_test_split

In [107]:
X_train, X_test, y_train, y_test = train_test_split(X_evasao, y_evasao, test_size=0.4, random_state=42)

In [108]:
X_train.shape, y_train.shape

((11698, 17), (11698,))

In [109]:
X_test.shape, y_test.shape

((7799, 17), (7799,))

#### Acurácia da evasão com KNN

In [110]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

knn.score(X_test, y_test)

0.85459674317220158

In [111]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

knn.score(X_test, y_test)

0.83587639440953965

In [112]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)

knn.score(X_test, y_test)

0.87549685857161175

-- Com 40% da base, a acurácia se torna melhor com 1 vizinho (0,85)

-- Com 60% da base, a acurácia se torna melhor com 1 vizinho (0,84)

-- Com 10% da base, a acurácia se torna melhor com 1 vizinho (0,87)

#### Acurácia da evasão com Árvore de Decisão

In [113]:
from sklearn import tree
tree = tree.DecisionTreeClassifier()
tree.fit(X_train, y_train)
tree.score(X_test,y_test)

0.97589434542890119

#### Acurácia da evasão com SVM

In [114]:
from sklearn import svm
svm = svm.SVC()
svm.fit(X_train, y_train)
svm.score(X_test,y_test)

0.84331324528785745